PrideInLondon/pride-london-web

- src/Features/Blog/Components/title/_spec.js
- src/Features/Blog/Components/title/index.js
- src/Features/Blog/Components/viewsCard/__snapshots__/_spec.js.snap
- src/Features/Blog/Components/viewsCard/_spec.js
- src/Features/Blog/Components/viewsCard/index.js
- src/Features/Blog/Containers/viewsContainer/__snapshots__/_spec.js.snap
- src/Features/Blog/Containers/viewsContainer/_spec.js
- src/Features/Blog/Containers/viewsContainer/index.js
Adds container and components with dummy data. Eventually the data would ideally be passed down as props from the container. 
So far tests are simply snapshot tests as they're quick to write and there isn't much functionality happening here anyway 😛
> feature Add ViewsCard, ViewsContainer, and Title Components

- src/components/bannerSubtitle/__snapshots__/_spec.js.snap
- src/components/bannerSubtitle/_spec.js
- src/components/bannerTitle/__snapshots__/_spec.js.snap
- src/components/bannerTitle/_spec.js
- src/components/button/__snapshots__/_spec.js.snap
- src/components/button/_spec.js
- src/components/checkbox/__snapshots__/_spec.js.snap
- src/components/checkbox/_spec.js
- src/components/checkboxSet/__snapshots__/_spec.js.snap
- src/components/checkboxSet/_spec.js
- src/components/chevronRight/__snapshots__/_spec.js.snap
- src/components/chevronRight/_spec.js
- src/components/footer/index.js
- src/components/image/__snapshots__/_spec.js.snap
- src/components/image/_spec.js
- src/components/imageBanner/__snapshots__/_spec.js.snap
- src/components/imageBanner/_spec.js
- src/components/navigation/tests/__snapshots__/header_test.js.snap
- src/components/navigation/tests/__snapshots__/navItems_test.js.snap
- src/components/navigation/tests/__snapshots__/navigation_test.js.snap
- src/components/navigation/tests/header_test.js
- src/components/navigation/tests/navItems_test.js
- src/components/navigation/tests/navigation_test.js
> Update tests syntax

- CONTRIBUTING.md
- README.md
Adding a CONTRIBUTING.md file for new starters and updating the README file removing the old link to Marcel repo
> Adding a CONTRIBUTING.md file

- .env.example
- README.md
- gatsby-config.js
- gatsby-node.js
- package-lock.json
- package.json
- yarn.lock
Testing Netlify deployment settings
- Add Netlify badge on README file
- Update environment variables naming convention
- Move dotenv package to dependency
- Add gatsby-source-filesystem
- Fix uppercase to lowercase on gatsby-node.js
- Remove deploy:ci script
- Implement Rollbar agent
> Add Netlify badge on README file

- src/components/nav/__snapshots__/_spec.js.snap
- src/components/nav/_spec.js
- src/components/nav/index.js
- src/components/submenu/__snapshots__/_spec.js.snap
- src/components/submenu/index.js
- src/components/submenu/styles.js
- Update navigation with Notion sitemap
- Refactor submenu styles file
> Navigation Menu Update

- src/pages/support-us/sponsors.js
add subject param to mailto link
> [QA #209] Partners Section - Email us button

- src/features/sponsors/components/sponsorBadge/index.js
- src/layouts/index.css
- src/pages/events.js
- src/templates/genericContentPage.js
…nd, fix sponsors page badges to have grey background, remove link underline on sponsors badges
> [QA #235] Partners Section - Background color

- LICENSE
Add Apache License, remove MIT License
> [GitHub] Add an open source licence

- src/components/banner/bannerImage/__snapshots__/_spec.js.snap
- src/components/banner/bannerImage/_spec.js
- src/components/banner/bannerImage/index.js
- src/components/banner/bannerSubtitle/styles.js
- src/features/blog/components/viewsCard/_spec.js
- src/features/blog/components/viewsCard/index.js
- src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
- src/features/blog/containers/viewsContainer/_mocks.js
- src/features/blogDetails/components/author/_spec.js
- src/features/blogDetails/components/author/index.js
- src/features/genericContentPage/__snapshots__/_spec.js.snap
- src/features/genericContentPage/_mocks.js
- src/features/genericContentPage/components/figure/__snapshots__/_spec.js.snap
- src/features/genericContentPage/components/figure/_spec.js
- src/features/genericContentPage/components/figure/index.js
- src/layouts/index.css
- src/pages/blog.js
- src/pages/index.js
- src/pages/privacy-policy.js
- src/templates/blogDetails.js
Author fields are long text instead of short text for display name etc. had to fix it in contentful and queries/usage in code
> Fix author fields

- src/layouts/index.js
- src/pages/events/whats-on.js
PR Template
update title tag and banner for events page
> [MVP] [QA] SEO - Change Description #380

- src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
- src/features/homepage/components/featuredEvents/_mocks.js
- src/features/homepage/components/featuredEvents/_spec.js
- src/features/homepage/components/featuredEvents/featuredEventsQuery.js
- src/features/homepage/components/featuredEvents/index.js
- src/pages/index.js
Make featured events carousel only display featured events instead of all events
> [MVP] [QA] Homepage - Featured Events

- src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
- src/features/blog/components/newsCard/index.js
- src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
Fix issue where news cards on blog landing page render as divs not Links
> News Card Link

- src/pages/index.js
> Hero banner copy + link

- src/components/banner/bannerImage/__snapshots__/_spec.js.snap
- src/components/banner/bannerImage/index.js
- src/components/banner/bannerImage/styles.js
- src/features/blog/components/newsCard/styles.js
- src/features/blog/containers/viewsContainer/index.js
- src/pages/blog.js
> [QA2] Blog Page #399

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Fix donate link for navigation

- src/features/blogDetails/components/blogContent/styles.js
- src/features/blogDetails/components/blogFooter/__snapshots__/_spec.js.snap
- src/features/blogDetails/components/blogFooter/index.js
- src/features/blogDetails/components/blogFooter/styles.js
- src/features/blogDetails/components/blogHeader/styles.js
- src/features/events/components/eventTagList.js
- src/templates/event.js
Fixes styling issues on blog details and event details pages
> [QA2] Blog Detail Page #394

- src/pages/support-us/partners.js
> [QA2] Sponsors Page #397

- src/layouts/index.css
- src/templates/genericContentPage.js
Fixes styling issues on generic content pages
> [QA2] Generic Page #393

- src/pages/events/whats-on.js
Sorts events in chronological order
> [QA2] Events Page #398

- README.md
- Netifly URL has changed
- Issue board URL has changed
> Update links within README

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Navigation wording adjustments

- src/pages/support-us/partners.js
> Add link to partnership packages doc

- src/components/footer/styles.js
- static/_redirects
> add redirects and remove greyscale on footer logos

- static/_headers
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options
> Implement Security Headers

- src/pages/news-and-views.js
> [QA #442] Organise Views by Date Published

- src/pages/support-us/partners.js
> Sort sponsors alphabetically

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Update navigation copy

- static/_redirects
Adds redirect for jubilee -> campaigns/about-us/jubilee
> Add redirect for /jubilee

- src/components/grid/index.js
- src/components/navigation/navItem/styles.js
- src/layouts/index.css
- src/layouts/index.js
set max-width wrapper on site to stop banner images from getting too blury, reduce nav font size
> Refactoring banner image

- src/features/homepage/containers/latestNewsContainer/styles.js
> fix z-index of latest news so img doesn't go behind sitewrapper

- src/features/paradeGroups/containers/paradeGroupsContainer/index.js
Fixes the duplicate '#' parade group
> Fix duplicate parade group

- src/components/button/index.js
- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
- src/features/genericContentPage/__snapshots__/_spec.js.snap
- src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
- yarn.lock
> Update Merchandise navigation URL

- src/features/events/components/eventsYouMayLike.js
> Related events view fix

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
add link to events/festival in nav
> Add Festival link to Nav

- src/components/newsCardHeader/index.js
- src/components/newsMetrics/index.js
- src/features/blog/components/newsCard/index.js
- src/features/blog/containers/newsCards/index.js
- src/features/blog/containers/newsContainer/index.js
- src/features/genericContentPage/renderMethods.js
- readTime proptype
- renderMethod return fix
> ReadTime proptype, renderMethod return fix

- src/templates/genericContentPage.js
> Banner image fix

- src/components/checkboxSet/_spec.js
- src/components/checkboxSet/index.js
- src/features/events/components/eventsFilters.js
- src/features/events/filters/eventDropdownFilter.js
- Alphabetise the category and accessibility filter list
> Alphabetise the category and accessibility filter list

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Add stalls page to stalls menu

- src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
- src/features/homepage/components/featuredEvents/slickSettings.js
- src/features/homepage/components/featuredEvents/styles.js
Arrows were not appearing on featured events carousel. Overrode the positioning and bumped the x axis of the arrows to be tighter around the main slider container.
> Bug on homepage slider

- src/features/paradeGroups/containers/paradeGroupsFiltersContainer/__snapshots__/_spec.js.snap
- src/features/paradeGroups/containers/paradeGroupsFiltersContainer/index.js
- src/features/paradeGroups/containers/paradeGroupsFiltersContainer/styles.js
- Parade groups filter label added
> Parade groups filter label added

- src/pages/parade-groups.js
- content indentation removed
- subheading changed
> Content indentation removed, subheading changed

- src/features/paradeGroups/components/letterLink/__snapshots__/_spec.js.snap
- src/features/paradeGroups/components/letterLink/index.js
- src/features/paradeGroups/components/letterLink/styles.js
> Disabled letter links fix

- src/features/paradeGroups/components/paradeGroup/styles.js
1. Parade group name color changed
> Parade Groups name color changed

- src/features/paradeGroups/components/letterLink/styles.js
- src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
- Scrolling alphabet design fix
> Scrolling alphabet design fix

- src/pages/parade-groups.js
> Parade groups text added

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Remove nav link

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
- src/components/navigation/submenu/styles.js
- yarn.lock
- Update links in nav menu
- Format to have 3 columns instead of 2 in nav menu
> Update links in nav menu

- src/components/cookieNotice/__snapshots__/_spec.js.snap
- src/components/cookieNotice/index.js
- Hide cookie banner dismiss button
> Hide cookie banner dismiss button

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
- Partner with us copy changed
> Partner with us copy changed

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
> Update menu links in nav bar

- package.json
- src/components/intercom/index.js
- src/pages/parade-groups.js
- src/pages/support-us/partners.js
- yarn.lock
Closes issue https://github.com/PrideInLondon/pride-london-web/issues/627.
> Added Intercom component

- src/layouts/index.js
- src/pages/support-us/partners.js
Intercom should be on every pages
> Add Intercom on every pages

- src/components/footer/styles.js
> [QA] Footer logos IE fix

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
- Family Area added
https://github.com/PrideInLondon/pride-london-web/issues/673
https://github.com/PrideInLondon/pride-london-web/issues/674
> Line up - Family Area added

- src/components/footer/__snapshots__/_spec.js.snap
- src/components/footer/_spec.js
- src/components/footer/index.js
- src/components/footer/styles.js
- FAQs
- Contact us - Intercom show
https://github.com/PrideInLondon/pride-london-web/issues/676
> Footer changes

- src/templates/blogDetails.js
- headline added
- article body added
https://github.com/PrideInLondon/pride-london-web/issues/111
> News&Views microdata fix

- src/pages/support-us/partners.js
> [QA] Partner with us page - spacing fix

- src/pages/parade/map/__snapshots__/_spec.js.snap
- src/pages/parade/map/index.js
> Parade Map PDF link

- src/layouts/index.js
- src/pages/events.js
- iOS app prompt on every site
> iOS app prompt on every site

- src/components/navigation/submenu/index.js
- src/components/newsCardHeader/index.js
- src/components/newsMetrics/index.js
- src/features/blog/components/featuredArticle/index.js
- src/features/blog/components/newsCard/index.js
- src/features/blog/components/viewsCard/index.js
- src/features/blog/containers/newsCards/index.js
- src/features/blog/containers/newsContainer/index.js
- src/features/blogDetails/components/blogHeader/index.js
- src/features/blogDetails/containers/pageHeader/index.js
- src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
- src/features/homepage/components/latestNews/_spec.js
- src/features/homepage/components/latestNews/index.js
- src/pages/news-and-views.js
- src/pages/parade/groups.js
- yarn.lock
> Linter fixes

- src/features/events/components/eventInfoCard.js
- src/features/events/helpers/index.js
- Moment formatting event date fix
> Moment formatting event date fix

- src/components/appContext/index.js
- src/features/events/filters/eventDropdownFilter.js
- src/features/help/components/dropDown.js
- src/templates/event.js
https://github.com/PrideInLondon/pride-london-web/issues/737
https://github.com/PrideInLondon/pride-london-web/issues/738
https://github.com/PrideInLondon/pride-london-web/issues/739
https://github.com/PrideInLondon/pride-london-web/issues/740
> LGTM fixes

- gatsby-node.js
- src/features/events/helpers/index.js
> Recurrence event page fix

- static/_redirects
> Rainbow planet redirect

- src/components/footer/__snapshots__/_spec.js.snap
- src/components/footer/index.js
- src/components/footer/styles.js
- src/components/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
- src/components/sponsors/components/sponsorBadge/styles.js
Sponsor logos size
https://github.com/PrideInLondon/pride-london-web/issues/213
> Sponsor logos size

- src/features/blogDetails/components/blogContent/renderMethods.js
- src/features/genericContentPage/renderMethods.js
- src/layouts/index.css
- src/pages/privacy.js
https://github.com/PrideInLondon/pride-london-web/issues/743
https://github.com/PrideInLondon/pride-london-web/issues/744
https://github.com/PrideInLondon/pride-london-web/issues/745
https://github.com/PrideInLondon/pride-london-web/issues/746
> SonarCloud fixes

- src/features/exploreLondon/components/communityPartnerCard/index.js
> Explore London - address line 2 fix

- src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
- src/features/homepage/components/featuredEvents/index.js
- src/features/homepage/components/featuredEvents/slickSettings.js
- src/features/homepage/components/featuredEvents/styles.js
> Homepage - featured events

- src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
- src/features/homepage/components/featuredEvents/featuredEventsQuery.js
- src/features/homepage/components/featuredEvents/index.css
- src/features/homepage/components/featuredEvents/index.js
- src/features/homepage/components/featuredEvents/slickSettings.js
- src/features/homepage/components/featuredEvents/styles.js
- sliders width fix
- featured events chronological order
> Homepage sections fix

- src/layouts/index.js
- src/pages/index.js
- hide download app section
- app prompts
https://github.com/PrideInLondon/pride-london-web/issues/762
> Hide app promos

- src/features/homepage/components/featuredEvents/featuredEventsQuery.js
- Homepage featured recurrence events fix
> Homepage featured recurrence events

- src/pages/index.js
- Help keep Pride free button added
> Help keep Pride free button

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
Fixes issue https://github.com/PrideInLondon/pride-london-web/issues/826
> Removed line up section from main navigation

- src/features/events/filters/eventDropdownFilter.js
Fixes issue https://github.com/PrideInLondon/pride-london-web/issues/671
> Added an overflow to the event filter dropdown

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
Closes issue https://github.com/PrideInLondon/pride-london-web/issues/880.
> Added line up section back into the navigation

- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
Closes issue https://github.com/PrideInLondon/pride-london-web/issues/880.
> Updated "family area" in nav bar

- src/components/banner/bannerImage/__snapshots__/_spec.js.snap
- src/components/banner/bannerImage/index.js
- src/components/banner/bannerImage/styles.js
- src/components/navigation/nav/__snapshots__/_spec.js.snap
- src/components/navigation/nav/index.js
- src/features/homepage/components/volunteerBoxInfo/styles.js
- src/features/homepage/containers/announcementsContainer/index.js
- src/features/homepage/containers/donateContainer/styles.js
- src/features/homepage/containers/latestNewsContainer/styles.js
- src/pages/index.js
Closes issue https://github.com/PrideInLondon/pride-london-web/issues/970.
> Post-events homepage

- src/templates/event.js
> WER-34 Updated event template to functional component

- src/templates/genericContentPage.js
> WER-35 Updated generic content page to functional component

- .eslintrc.js
- gatsby-node.js
- package.json
- src/components/appContext/index.js
- src/features/events/components/eventListingCard.js
- src/features/events/helpers/index.js
- src/features/events/helpers/index.test.js
- src/features/homepage/components/featuredEvents/featuredEventsQuery.js
- yarn.lock
> EVE-2 event url rewrite for SEO optimisation

- .remarkrc
- README.md
- SECURITY.md
- package.json
- yarn.lock
> WER-40 update pre commit to include markdown formatter

- src/components/navigation/nav/__snapshots__/index.test.js.snap
- src/components/navigation/nav/index.js
> WEBNEW-45: ♻️ Update menu for Take Part Generic Page

- README.md
Codacy and Snyk badges have been removed
> WEBREF-45: ♻️Update README to remove Codacy badge

- src/features/events/helpers/index.js
> WEBNEW-54: events missing from site

- src/components/navigation/nav/__snapshots__/index.test.js.snap
- src/components/navigation/nav/index.js
> WEBNEW-64 ♻️Add Pride's Got Talent on menu

- package.json
- src/features/events/filters/eventDateFilter/eventDateFilter.styles.ts
- src/features/events/filters/eventDateFilter/eventDateFilter.tsx
- src/features/events/filters/eventDateFilter/eventDateFilter.types.ts
- src/features/events/filters/eventDateFilter/index.ts
- src/types/generic.ts
- src/types/index.ts
- yarn.lock
> WEBREF-20 ♻️ Refactor eventDateFilter to hooks and typescript

- src/homepage/Announcements.styles.js
- src/homepage/announcementsSlickSettings.js
Updated the carousel settings for the homepage.
> WEBREF-32 🐛 Fixed centering issue on homepage carousel

- src/homepage/HomePage.js
> WEBNEW-92 ♻️ Remove date from homepage

- src/events/EventsPageBanner.styles.ts
- src/events/EventsPageBanner.tsx
- src/events/GroupedEventsCards.js
Added a link for the "get your event listed" page on coming out homepage.
Also removed some dead code and fixed a JS error occurring on that page.
> WEBNEW-95 ✨ Get your event listed link

- src/layout/footer/Footer.js
- src/sponsors/PartnersPage.js
Updated both footer and partner with us pages to reflect partners were from 2019 and not current.
> WEBNEW-98 💬 Updated copy for 2019 partners

- src/events/event/EventPage.js
- src/events/helpers.js
- src/events/helpers.test.js
This includes removing map for virtual events.
> WEBNEW-109 🚸 Removed requirement for event to have physical location

- src/components/icons/LaptopIcon.tsx
- src/components/icons/index.js
- src/events/__mocks__/index.js
- src/events/event/EventInfoCard.js
- src/events/event/EventInfoCard.test.js
- src/events/event/EventPage.js
- src/events/helpers.js
- src/events/helpers.test.js
This is on the individual event page. The general events update will follow this one.
> WEBNEW-106 ✨ Show laptop icon and virtual location when virtual event

- gatsby-node.esm.js
- src/events/helpers.js
- src/events/helpers.test.js
- src/layout/Layout.js
- yarn.lock
This PR refactors how past events are filtered and sorted, using the new date field (the custom ui extension for recurring event dates).
> WEBNEW-112 Filter Past Events

- static/_redirects
> WEBNEW-117 🔧 Added redirect for campaign applications

- src/parade/ParadeGroupsPage.js
> WEBNEW-138 📝 Update Parage Groups page copy

- README.md
> DSO-28 📝 Add GuardRails badge on README file

- src/layout/footer/Footer.js
- src/sponsors/PartnersPage.js
- Updated copy for 2020 sponsors
- Fixed bug for showing Gold sponsors
> WEBNEW-145 💬 Update copy for 2020 sponsors

- src/layout/navigation/Navigation.tsx
Ahead of YMUW launch tomorrow AM.
> WEBNEW-149 🔥 Removed ymuw from nav bar

- src/utils/share-utils.test.ts
- src/utils/share-utils.ts
> WEBNEW-151 🐛 Removed app id from fb share url

- src/campaigns/youMeUsWe/DonateToYourCommunitySection.tsx
> WEBNEW-158 💬 Update donation copy

- src/blog/article/BlogHeader.styles.js
- src/blog/article/OtherArticlesHeader.styles.js
- src/blog/article/blogContent/BlogContent.styles.js
- src/layout/Layout.styles.js
I've added the colour indigo to the article body, date of publish and links inside the body.
Ticket: https://prideinlondon.atlassian.net/browse/WEBNEW-172
> WEBNEW-172 💄 Font colour update

- src/layout/footer/Footer.js
- src/layout/footer/Footer.styles.js
This is a partial revert of 822ca89f4550b54a0a26dd559a8b924fee1dec97.
> WEBNEW-167 ✨ Re-added subscribe link to footer

- src/components/icon/Icon.tsx
- src/components/icon/Icon.utils.test.tsx
- src/components/icon/Icon.utils.ts
- src/components/modal/Modal.styles.tsx
- src/components/pageSwitcher/PageSwitcher.tsx
- src/fifty-two/AgeVerification.tsx
- Fix age verification font size and spacing of modal in mobile view.
- Fix icon so it doesnt flex shrink
- Refactor icon so it can accept a `mirror` prop
> WEBNEW-182 Entry page fixes

- src/fifty-two/renderMethods.tsx
This is for the Fifty-Two hub only.
> WEBNEW-196 💄 Updated body text links to match new design

- src/fifty-two/entry/FiftyTwoEntryPage.tsx
Updated to match designs and be inline with `Footer`.
> WEBNEW-197 💄 Bumped padding on Fifty-Two entry page

- src/blog/article/OtherArticlesHeader.js
- src/blog/article/OtherArticlesHeader.styles.js
Added `/news-and-views` href to View all articles link
> WEBNEW-60 🐛  Fixed news-and-views link

- .env.example
- README.md
- gatsby-config.js
Updated the Gatsby process to take in an optional `environment` option.
Cleared down the current process to make things more readable and accessible.
> DSO-66 🔧 Contentful environment

- src/components/playButton/PlayButton.styles.tsx
- src/components/playButton/PlayButton.tsx
- src/components/playButton/PlayButton.types.ts
- src/components/video/Video.styles.ts
- src/components/video/Video.test.tsx
- src/components/video/Video.tsx
Fixed small a11y and styling issues with the `PlayButton` and `Video` components.
Only affected live page will be the `/about-us/campaigns/you-me-us-we` page.
> WEBNEW-227 💄 Video component improved a11y and UX

- gatsby-config.js
- gatsby-node.esm.js
- src/blog/article/BlogArticlePage.tsx
- src/blog/article/helpers.test.ts
- src/blog/article/helpers.ts
- src/utils/page-utils.test.ts
- src/utils/page-utils.ts
Generate a single page per article published in Contentful. 
The URL structure for now will follow the structure `/blog/title-of-blog-article`.
> WEBNEW-215 🔧 Blog article page generation

- src/components/footer/Footer.tsx
Year has been updated in the footer
> WEBNEW-240 💬 Update date in the footer

- LICENSE
Updating PIL License to 2021 :)
> DSO-38 📄 Update PIL license for website

- src/blog/article/BlogArticlePage.styles.ts
- src/blog/article/BlogArticlePage.tsx
- src/blog/article/BlogArticlePage.types.ts
- src/components/categoryCard/CategoryCard.stories.tsx
- src/components/categoryCard/CategoryCard.styles.tsx
- src/components/categoryCard/CategoryCard.tsx
- src/components/categoryCard/CategoryCard.types.ts
- src/components/categoryCard/index.ts
- src/components/tag/Tag.styles.tsx
- src/components/tag/Tag.tsx
- src/components/tag/Tag.types.ts
- src/components/wrapper/Wrapper.tsx
- src/components/wrapper/Wrapper.types.ts
Including minor adjustment to the `Tag` component, to leverage the `Wrapper` component and avoid more custom `div` elements.
> WEBNEW-230 ✨ Blog article "You may also like" section

- src/homepage/HomePage.js
New date added on the homepage banner
> WEBNEW-246 💬 Update date on Hero Homepage

- src/layout/navigation/Navigation.tsx
> WEBNEW-262 Add stalls to navigation menu

- src/homepage/HomePage.js
- src/layout/navigation/Navigation.tsx
Show 2022 date and parade navigation
> WEBREF-123 :rocket: 2022 date launch

- static/_redirects
> WEBNEW-268 :mag: Add rbl redirect

- src/parade/ParadeMapPage.js
> WEBREF-123 :lipstick: Alter zoom and location-centre for Parade map view

- src/layout/navigation/Navigation.tsx
- src/parade/ParadeMapPage.js
> WEBNEW-269 :fire: Remove CTAs, change text and ctas

- src/layout/navigation/Navigation.tsx
> WEBNEW-269 :fire: Remove submenu

- static/_redirects
> WEBNEW-271 :sparkles: Add redirects for rbl

- src/layout/navigation/Navigation.tsx
> WEBNEW-273 :sparkles: Add Comms submenu option to About

- src/layout/navigation/Navigation.tsx
> WEBNEW-273 :sparkles: Add Accessibility

- src/sponsors/PartnersPage.tsx
> WEBNEW-273 :speech_balloon: Change partners text

- src/layout/navigation/Navigation.tsx
> WEBNEW-276 :bug: Remove parade

- src/layout/navigation/Navigation.tsx
> WEBNEW-276 :fire: Remove stall nav links

- src/constants.js
- src/sponsors/PartnersPage.tsx
> Dev early release

- src/layout/navigation/Navigation.tsx
> Update leicester square stage url

- src/homepage/HomePage.js
- src/layout/navigation/Navigation.tsx
- static/_redirects
- updated redirection url to the new parade2023 page
- updated redirection button on homepage
PR Template
> Parade 2023 redirection

- src/pages/parade/groups.js
> Parade Group filter update

- src/homepage/HomePage.js
- src/layout/navigation/Navigation.tsx
> Updated parade URL

- src/parade/ParadeGroup.js
- src/parade/ParadeGroup.styles.js
- src/parade/ParadeGroups.js
Added parade group description in the parade group section
> Added parade group description

- src/parade/ParadeGroupsPage.js
> Dev early release 2

- src/parade/ParadeGroupsPage.js
> text update

- src/layout/navigation/Navigation.tsx
> Unity Fund update

- src/layout/navigation/Navigation.tsx
Pride in the city update
PR Template
> Pride in the City Update

- src/layout/navigation/Navigation.tsx
> Updated navigations

- src/layout/navigation/Navigation.tsx
> parde entry path update

- src/layout/navigation/Navigation.tsx
> Update hire a stall

- src/layout/navigation/Navigation.tsx
> Navbar update

- src/components/footer/Footer.tsx
> 2024 partners update

- src/components/footer/Footer.tsx
- src/layout/navigation/Navigation.tsx
- src/sponsors/PartnersPage.tsx
- removed UPS
- updated 2023 to 2024
- updated navigations
PR Template
> Minor Update

- src/sponsors/PartnersPage.tsx
> Added ethical policy

- src/events/event/EventInfoCard.tsx
- src/events/event/EventInfoCard.types.ts
- src/events/event/EventPage.js
- updated reference to google maps
- remove google map embed
PR Template
> Event page changes

- src/layout/navigation/Navigation.tsx
> Forced commit

- src/homepage/AnnouncementCarousel.css
- src/homepage/AnnouncementCarousel.js
- src/homepage/AnnouncementCarouselCard.js
- src/homepage/AnnouncementCarouselCard.styles.js
> Fix transition effect issue on carousel

- src/homepage/AnnouncementCarousel.js
- src/homepage/AnnouncementCarouselCard.js
- src/homepage/AnnouncementCarouselCard.styles.js
- src/homepage/AnnouncementList.js
> Dev release carousel

- src/homepage/AnnouncementCarousel.js
to infinity and beyond
PR Template
> enable infinity scrolling for carousel

- src/homepage/HomePage.js
> Homepage content amended

- src/homepage/AnnouncementListCard.styles.js
> css update

- src/components/grid/Grid.js
- src/components/grid/Grid.styles.tsx
- src/components/grid/index.ts
- src/homepage/HighlightBanner.js
> Create new column style to fix highlight banner's height

- gatsby-config.js
> added new GTM

- src/components/button/Button.styles.tsx
> Adjusted fontsize on highlight banner

- src/events/event/EventPage.js
> Fix React markdown

- src/events/event/EventInfoCard.tsx
- src/events/event/EventPage.js
- src/events/event/EventPage.styles.js
update ui issues and event listings
PR Template
> Update event listings

- src/events/event/EventPage.js
> fix location lat/lon missing bug

- src/sponsors/sponsors.utils.ts
> added alpabetical sort

- src/parade/ParadeGroupsPage.js
> Parade group update

- src/layout/navigation/Navigation.tsx
> Add new site

- static/_redirects
> added redirect

- src/homepage/HomePage.js
- src/homepage/Livestream.js
> Added livestream
